import { useCallback, useEffect } from 'react'
import type React from 'react'
import type Konva from 'konva'
import { jsPDF } from 'jspdf'
import type { Project, PatchMapRow } from '../../../shared/types'

interface ExportFns {
  png: (() => void) | null
  pdf: (() => void) | null
}

interface UseExportHandlersConfig {
  stageRef: React.RefObject<Konva.Stage | null>
  activeProject: Project | null
  patchRows: PatchMapRow[]
  registerExport: (fns: ExportFns) => void
}

export function useExportHandlers({
  stageRef,
  activeProject,
  patchRows,
  registerExport
}: UseExportHandlersConfig): void {
  const exportPng = useCallback(() => {
    if (!stageRef.current || !activeProject) return
    const stage = stageRef.current
    const savedScaleX = stage.scaleX()
    const savedScaleY = stage.scaleY()
    const savedX = stage.x()
    const savedY = stage.y()
    stage.scaleX(1)
    stage.scaleY(1)
    stage.x(0)
    stage.y(0)
    const dataUrl = stage.toDataURL({ pixelRatio: 2 })
    stage.scaleX(savedScaleX)
    stage.scaleY(savedScaleY)
    stage.x(savedX)
    stage.y(savedY)
    const link = document.createElement('a')
    link.download = `${activeProject.name}.png`
    link.href = dataUrl
    link.click()
  }, [activeProject, stageRef])

  const exportPdf = useCallback(() => {
    if (!stageRef.current || !activeProject) return
    const stage = stageRef.current
    const savedScaleX = stage.scaleX()
    const savedScaleY = stage.scaleY()
    const savedX = stage.x()
    const savedY = stage.y()
    stage.scaleX(1)
    stage.scaleY(1)
    stage.x(0)
    stage.y(0)
    const w = stage.width()
    const h = stage.height()
    const dataUrl = stage.toDataURL({ pixelRatio: 2 })
    stage.scaleX(savedScaleX)
    stage.scaleY(savedScaleY)
    stage.x(savedX)
    stage.y(savedY)

    const pdf = new jsPDF({
      orientation: w > h ? 'landscape' : 'portrait',
      unit: 'px',
      format: [w, h],
      hotfixes: ['px_scaling']
    })
    pdf.addImage(dataUrl, 'PNG', 0, 0, w, h)

    // Append input list as page 2 if there are any rows
    if (patchRows.length > 0) {
      pdf.addPage('a4', 'portrait')
      appendInputListPage(pdf, activeProject.name, patchRows)
    }

    pdf.save(`${activeProject.name}.pdf`)
  }, [activeProject, patchRows, stageRef])

  useEffect(() => {
    registerExport({ png: exportPng, pdf: exportPdf })
  }, [exportPng, exportPdf, registerExport])
}

function appendInputListPage(doc: jsPDF, projectName: string, rows: PatchMapRow[]): void {
  const PW = doc.internal.pageSize.getWidth()
  const PH = doc.internal.pageSize.getHeight()
  const MARGIN = 40
  const TABLE_W = PW - MARGIN * 2
  const COL_CH = 44
  const COL_NAME = TABLE_W - COL_CH
  const ROW_H = 22

  // Title
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.setTextColor(30, 30, 30)
  doc.text('Input List', MARGIN, MARGIN + 16)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(120, 120, 120)
  doc.text(projectName, MARGIN, MARGIN + 28)

  const date = new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })
  doc.text(date, PW - MARGIN, MARGIN + 28, { align: 'right' })

  const HEADER_Y = MARGIN + 44

  // Header row
  doc.setFillColor(28, 28, 36)
  doc.rect(MARGIN, HEADER_Y, TABLE_W, ROW_H, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.setTextColor(200, 200, 210)
  doc.text('#', MARGIN + COL_CH / 2, HEADER_Y + 14, { align: 'center' })
  doc.text('INPUT', MARGIN + COL_CH + 6, HEADER_Y + 14)

  // Column separator in header
  doc.setDrawColor(60, 60, 80)
  doc.line(MARGIN + COL_CH, HEADER_Y, MARGIN + COL_CH, HEADER_Y + ROW_H)

  let y = HEADER_Y + ROW_H

  rows.forEach((row, idx) => {
    if (idx % 2 === 1) {
      doc.setFillColor(246, 246, 250)
      doc.rect(MARGIN, y, TABLE_W, ROW_H, 'F')
    }

    doc.setDrawColor(220, 220, 228)
    doc.line(MARGIN, y + ROW_H, MARGIN + TABLE_W, y + ROW_H)
    doc.line(MARGIN + COL_CH, y, MARGIN + COL_CH, y + ROW_H)

    // Channel number
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.setTextColor(30, 30, 30)
    doc.text(String(idx + 1), MARGIN + COL_CH / 2, y + 14, { align: 'center' })

    // Name
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(30, 30, 30)
    const clipped = doc.splitTextToSize(row.name || '—', COL_NAME - 12)
    doc.text(clipped[0], MARGIN + COL_CH + 6, y + 14)

    y += ROW_H

    if (y > PH - MARGIN - ROW_H) {
      doc.addPage()
      y = MARGIN
    }
  })

  // Outer border
  doc.setDrawColor(180, 180, 188)
  doc.rect(MARGIN, HEADER_Y, TABLE_W, y - HEADER_Y)

  // Footer
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7)
  doc.setTextColor(160, 160, 160)
  doc.text('Generated by Stage Plot', MARGIN, PH - 20)
  doc.text(`${rows.length} input${rows.length !== 1 ? 's' : ''}`, PW - MARGIN, PH - 20, { align: 'right' })
}
