import { jsPDF } from 'jspdf'
import type { StageItem, BaseExtra } from '../../../shared/types'
import { isPatchableType } from '../../../shared/itemExtras'

export function exportInputListPdf(items: StageItem[], projectName: string): void {
  const patchItems = items
    .filter((i) => isPatchableType(i.type))
    .sort((a, b) => {
      const pA = (a.extra as BaseExtra | null)?.patchNumber ?? Infinity
      const pB = (b.extra as BaseExtra | null)?.patchNumber ?? Infinity
      if (pA !== pB) return pA - pB
      return a.sort_order - b.sort_order
    })

  const doc = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'a4' })

  const PW = doc.internal.pageSize.getWidth()
  const PH = doc.internal.pageSize.getHeight()
  const MARGIN = 40
  const TABLE_W = PW - MARGIN * 2

  const COL_CH = 40
  const COL_NOTES = 170
  const COL_INPUT = TABLE_W - COL_CH - COL_NOTES
  const ROW_H = 22

  // Title
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.setTextColor(30, 30, 30)
  doc.text('Input List', MARGIN, MARGIN + 18)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(120, 120, 120)
  doc.text(projectName, MARGIN, MARGIN + 34)

  const date = new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })
  doc.text(date, PW - MARGIN, MARGIN + 34, { align: 'right' })

  const HEADER_Y = MARGIN + 52

  // Header row
  doc.setFillColor(28, 28, 36)
  doc.rect(MARGIN, HEADER_Y, TABLE_W, ROW_H, 'F')

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.setTextColor(200, 200, 210)
  doc.text('#', MARGIN + COL_CH / 2, HEADER_Y + 14, { align: 'center' })
  doc.text('INPUT', MARGIN + COL_CH + 6, HEADER_Y + 14)
  doc.text('NOTES', MARGIN + COL_CH + COL_INPUT + 6, HEADER_Y + 14)

  // Column separator lines in header
  doc.setDrawColor(60, 60, 80)
  doc.line(MARGIN + COL_CH, HEADER_Y, MARGIN + COL_CH, HEADER_Y + ROW_H)
  doc.line(MARGIN + COL_CH + COL_INPUT, HEADER_Y, MARGIN + COL_CH + COL_INPUT, HEADER_Y + ROW_H)

  let y = HEADER_Y + ROW_H

  patchItems.forEach((item, idx) => {
    const base = item.extra as BaseExtra | null
    const chNum = base?.patchNumber
    const label = base?.inputLabel || item.label
    const notes = base?.patchNotes ?? ''

    // Alternating row background
    if (idx % 2 === 1) {
      doc.setFillColor(246, 246, 250)
      doc.rect(MARGIN, y, TABLE_W, ROW_H, 'F')
    }

    // Row bottom border
    doc.setDrawColor(220, 220, 228)
    doc.line(MARGIN, y + ROW_H, MARGIN + TABLE_W, y + ROW_H)

    // Column separators
    doc.setDrawColor(220, 220, 228)
    doc.line(MARGIN + COL_CH, y, MARGIN + COL_CH, y + ROW_H)
    doc.line(MARGIN + COL_CH + COL_INPUT, y, MARGIN + COL_CH + COL_INPUT, y + ROW_H)

    // Channel number (bold, centered)
    if (chNum !== undefined) {
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(9)
      doc.setTextColor(30, 30, 30)
      doc.text(String(chNum), MARGIN + COL_CH / 2, y + 14, { align: 'center' })
    } else {
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(9)
      doc.setTextColor(180, 180, 180)
      doc.text('—', MARGIN + COL_CH / 2, y + 14, { align: 'center' })
    }

    // Input label
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(30, 30, 30)
    const labelClipped = doc.splitTextToSize(label, COL_INPUT - 12)
    doc.text(labelClipped[0], MARGIN + COL_CH + 6, y + 14)

    // Notes
    doc.setFontSize(8)
    doc.setTextColor(100, 100, 110)
    const notesClipped = doc.splitTextToSize(notes, COL_NOTES - 12)
    if (notesClipped[0]) {
      doc.text(notesClipped[0], MARGIN + COL_CH + COL_INPUT + 6, y + 14)
    }

    y += ROW_H

    if (y > PH - MARGIN - ROW_H) {
      doc.addPage()
      y = MARGIN
    }
  })

  // Outer border
  doc.setDrawColor(180, 180, 188)
  doc.rect(MARGIN, HEADER_Y, TABLE_W, y - HEADER_Y)

  // Footer
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7)
  doc.setTextColor(160, 160, 160)
  doc.text('Generated by Stage Plot', MARGIN, PH - 20)
  doc.text(`${patchItems.length} input${patchItems.length !== 1 ? 's' : ''}`, PW - MARGIN, PH - 20, { align: 'right' })

  doc.save(`${projectName} - Input List.pdf`)
}
